import type { SpellDef } from '@/types/spells';

export const SPELLS_L4_L5 = [
  {
    id: 'aura-of-purity',
    level: 4,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self (30-foot emanation)',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 10 minutes',
    nativeClasses: ['cleric', 'paladin'],
  },
  {
    id: 'control-water',
    level: 4,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '300 feet',
    components: { verbal: true, somatic: true, material: 'a mixture of water and dust' },
    duration: 'Up to 10 minutes',
    nativeClasses: ['cleric', 'druid', 'wizard'],
  },
  {
    id: 'divination',
    level: 4,
    school: 'divination',
    ritual: true,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: {
      verbal: true,
      somatic: true,
      material: 'incense and a sacrificial offering worth 25+ GP, which the spell consumes',
    },
    duration: 'Instantaneous',
    nativeClasses: ['cleric', 'druid', 'wizard'],
  },
  {
    id: 'conjure-minor-elementals',
    level: 4,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 10 minutes',
    nativeClasses: ['druid', 'wizard'],
  },
  {
    id: 'conjure-woodland-beings',
    level: 4,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self (10-foot emanation)',
    components: { verbal: true, somatic: true, material: 'a sprig of mistletoe' },
    duration: 'Up to 10 minutes',
    nativeClasses: ['druid', 'ranger'],
  },
  {
    id: 'fabricate',
    level: 4,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['wizard'],
  },
  {
    id: 'find-greater-steed',
    level: 4,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['paladin'],
  },
  {
    id: 'fount-of-moonlight',
    level: 4,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 10 minutes',
    nativeClasses: ['bard', 'druid'],
  },
  {
    id: 'giant-insect',
    level: 4,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 10 minutes',
    nativeClasses: ['druid'],
  },
  {
    id: 'grasping-vine',
    level: 4,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['druid', 'ranger'],
  },
  {
    id: 'hallucinatory-terrain',
    level: 4,
    school: 'illusion',
    ritual: false,
    concentration: false,
    castingTime: '10 minutes',
    range: '300 feet',
    components: { verbal: true, somatic: true, material: 'a mushroom' },
    duration: '24 hours',
    nativeClasses: ['bard', 'druid', 'warlock', 'wizard'],
  },
  {
    id: 'leomunds-secret-chest',
    level: 4,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a chest worth 5,000+ GP and a Tiny replica worth 50+ GP' },
    duration: 'Until dispelled',
    nativeClasses: ['wizard'],
  },
  {
    id: 'locate-creature',
    level: 4,
    school: 'divination',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'fur from a bloodhound' },
    duration: 'Up to 1 hour',
    nativeClasses: ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'wizard'],
  },
  {
    id: 'mordenkainens-faithful-hound',
    level: 4,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a tiny silver whistle' },
    duration: '8 hours',
    nativeClasses: ['wizard'],
  },
  {
    id: 'mordenkainens-private-sanctum',
    level: 4,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '120 feet',
    components: {
      verbal: true,
      somatic: true,
      material: 'a thin sheet of lead, a piece of opaque glass, and a wad of cotton',
    },
    duration: '24 hours',
    nativeClasses: ['wizard'],
  },
  {
    id: 'otilukes-resilient-sphere',
    level: 4,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '30 feet',
    components: {
      verbal: true,
      somatic: true,
      material: 'a hemispherical piece of translucent glass and a matching hemisphere of gum arabic',
    },
    duration: 'Up to 1 minute',
    nativeClasses: ['wizard'],
  },
  {
    id: 'phantasmal-killer',
    level: 4,
    school: 'illusion',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['bard', 'wizard'],
  },
  {
    id: 'sickening-radiance',
    level: 4,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 10 minutes',
    nativeClasses: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'staggering-smite',
    level: 4,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['paladin'],
  },
  {
    id: 'stone-shape',
    level: 4,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'soft clay' },
    duration: 'Instantaneous',
    nativeClasses: ['cleric', 'druid', 'wizard'],
  },
  {
    id: 'summon-elemental',
    level: 4,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '90 feet',
    components: {
      verbal: true,
      somatic: true,
      material: 'air, a pebble, ash, and water inside a gold-inlaid vessel worth 400+ GP',
    },
    duration: 'Up to 1 hour',
    nativeClasses: ['druid', 'wizard'],
  },
  {
    id: 'summon-greater-demon',
    level: 4,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '60 feet',
    components: {
      verbal: true,
      somatic: true,
      material: 'a vial of blood from a humanoid killed within the past 24 hours',
    },
    duration: 'Up to 1 hour',
    nativeClasses: ['warlock', 'wizard'],
  },
  {
    id: 'vitriolic-sphere',
    level: 4,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '150 feet',
    components: { verbal: true, somatic: true, material: 'a drop of bile' },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  {
    id: 'antilife-shell',
    level: 5,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self (10-foot emanation)',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 hour',
    nativeClasses: ['druid'],
  },
  {
    id: 'awaken',
    level: 5,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '8 hours',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'an agate worth 1,000+ GP, which the spell consumes' },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'druid'],
  },
  {
    id: 'banishing-smite',
    level: 5,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['paladin'],
  },
  {
    id: 'bigbys-hand',
    level: 5,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'an eggshell and a snakeskin glove' },
    duration: 'Up to 1 minute',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  {
    id: 'circle-of-power',
    level: 5,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self (30-foot emanation)',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 10 minutes',
    nativeClasses: ['paladin'],
  },
  {
    id: 'cloudkill',
    level: 5,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 10 minutes',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  {
    id: 'conjure-elemental',
    level: 5,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 10 minutes',
    nativeClasses: ['druid', 'wizard'],
  },
  {
    id: 'conjure-volley',
    level: 5,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '150 feet',
    components: { verbal: true, somatic: true, material: 'one piece of ammunition or one Thrown weapon' },
    duration: 'Instantaneous',
    nativeClasses: ['ranger'],
  },
  {
    id: 'contact-other-plane',
    level: 5,
    school: 'divination',
    ritual: true,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: false, material: false },
    duration: '1 minute',
    nativeClasses: ['warlock', 'wizard'],
  },
  {
    id: 'contagion',
    level: 5,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: false },
    duration: '7 days',
    nativeClasses: ['cleric', 'druid'],
  },
  {
    id: 'creation',
    level: 5,
    school: 'illusion',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a paintbrush' },
    duration: 'Special',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  {
    id: 'dispel-evil-and-good',
    level: 5,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'holy water or powdered silver and iron' },
    duration: 'Up to 1 minute',
    nativeClasses: ['cleric', 'paladin'],
  },
  {
    id: 'dream',
    level: 5,
    school: 'illusion',
    ritual: false,
    concentration: false,
    castingTime: '1 minute',
    range: 'Special',
    components: { verbal: true, somatic: true, material: 'a handful of sand' },
    duration: '8 hours',
    nativeClasses: ['bard', 'warlock', 'wizard'],
  },
  {
    id: 'hallow',
    level: 5,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: '24 hours',
    range: 'Touch',
    components: {
      verbal: true,
      somatic: true,
      material: 'herbs, oils, and incense worth 1,000+ GP, which the spell consumes',
    },
    duration: 'Until dispelled',
    nativeClasses: ['cleric'],
  },
  {
    id: 'holy-weapon',
    level: 5,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 hour',
    nativeClasses: ['cleric', 'paladin'],
  },
  {
    id: 'jallarzis-storm-of-radiance',
    level: 5,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a pinch of phosphorus and a splash of water' },
    duration: 'Up to 1 minute',
    nativeClasses: ['warlock', 'wizard'],
  },
  {
    id: 'passwall',
    level: 5,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a pinch of sesame seeds' },
    duration: '1 hour',
    nativeClasses: ['wizard'],
  },
  {
    id: 'planar-binding',
    level: 5,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: '1 hour',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a jewel worth 1,000+ GP, which the spell consumes' },
    duration: '24 hours',
    nativeClasses: ['bard', 'cleric', 'druid', 'warlock', 'wizard'],
  },
  {
    id: 'raise-dead',
    level: 5,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: '1 hour',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a diamond worth 500+ GP, which the spell consumes' },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'cleric', 'paladin'],
  },
  {
    id: 'reincarnate',
    level: 5,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '1 hour',
    range: 'Touch',
    components: {
      verbal: true,
      somatic: true,
      material: 'rare oils and unguents worth 1,000+ GP, which the spell consumes',
    },
    duration: 'Instantaneous',
    nativeClasses: ['druid'],
  },
  {
    id: 'swift-quiver',
    level: 5,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a Quiver worth 1+ GP' },
    duration: 'Up to 1 minute',
    nativeClasses: ['ranger'],
  },
  {
    id: 'synaptic-static',
    level: 5,
    school: 'enchantment',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'teleportation-circle',
    level: 5,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: '1 minute',
    range: '10 feet',
    components: { verbal: true, somatic: false, material: 'rare inks worth 50+ GP, which the spell consumes' },
    duration: '1 round',
    nativeClasses: ['bard', 'sorcerer', 'wizard'],
  },
  {
    id: 'wrath-of-nature',
    level: 5,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['druid', 'ranger'],
  },
] as const satisfies readonly SpellDef[];
