import type { SpellDef } from '@/types/spells';

export const SPELLS_L6_L9 = [
  {
    id: 'arcane-gate',
    level: 6,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '500 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '10 minutes',
    nativeClasses: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'blade-barrier',
    level: 6,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '10 minutes',
    nativeClasses: ['cleric'],
  },
  {
    id: 'bones-of-the-earth',
    level: 6,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['druid'],
  },
  {
    id: 'chain-lightning',
    level: 6,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '150 feet',
    components: {
      verbal: true,
      somatic: true,
      material: 'a bit of fur, a rod of amber or glass, and three silver pins',
    },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  {
    id: 'circle-of-death',
    level: 6,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '150 feet',
    components: { verbal: true, somatic: true, material: 'powdered black pearl worth 500+ GP' },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'conjure-fey',
    level: 6,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '10 minutes',
    nativeClasses: ['druid', 'warlock'],
  },
  {
    id: 'contingency',
    level: 6,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: '10 minutes',
    range: 'Self',
    components: {
      verbal: true,
      somatic: true,
      material: 'a statuette of yourself carved from ivory and worth 1,500+ GP',
    },
    duration: '10 days',
    nativeClasses: ['wizard'],
  },
  {
    id: 'create-undead',
    level: 6,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: '1 minute',
    range: '10 feet',
    components: { verbal: true, somatic: true, material: 'a black onyx stone worth 150+ GP for each corpse' },
    duration: 'Instantaneous',
    nativeClasses: ['cleric', 'warlock', 'wizard'],
  },
  {
    id: 'disintegrate',
    level: 6,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a lodestone and a pinch of dust' },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  {
    id: 'drawmijs-instant-summons',
    level: 6,
    school: 'conjuration',
    ritual: true,
    concentration: false,
    castingTime: '1 minute',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a sapphire worth 1,000+ GP' },
    duration: 'Until dispelled',
    nativeClasses: ['wizard'],
  },
  {
    id: 'eyebite',
    level: 6,
    school: 'necromancy',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 minute',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'find-the-path',
    level: 6,
    school: 'divination',
    ritual: false,
    concentration: true,
    castingTime: '1 minute',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a set of divination tools' },
    duration: '1 day',
    nativeClasses: ['bard', 'cleric', 'druid'],
  },
  {
    id: 'forbiddance',
    level: 6,
    school: 'abjuration',
    ritual: true,
    concentration: false,
    castingTime: '10 minutes',
    range: 'Touch',
    components: {
      verbal: true,
      somatic: true,
      material: 'a sprinkle of holy water, rare incense, and powdered ruby worth 1,000+ GP',
    },
    duration: '1 day',
    nativeClasses: ['cleric'],
  },
  {
    id: 'globe-of-invulnerability',
    level: 6,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a glass or crystal bead' },
    duration: '1 minute',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  {
    id: 'guards-and-wards',
    level: 6,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: '10 minutes',
    range: 'Touch',
    components: {
      verbal: true,
      somatic: true,
      material: 'burning incense, a bit of sulfur and oil, a knotted string, and a lock of hair from a creature',
    },
    duration: '24 hours',
    nativeClasses: ['bard', 'wizard'],
  },
  {
    id: 'harm',
    level: 6,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['cleric'],
  },
  {
    id: 'heal',
    level: 6,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['cleric', 'druid'],
  },
  {
    id: 'heroes-feast',
    level: 6,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: '10 minutes',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a bowl worth 1,000+ GP' },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'cleric', 'druid'],
  },
  {
    id: 'magic-jar',
    level: 6,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: '1 minute',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a gem, crystal, or reliquary worth 500+ GP' },
    duration: 'Until dispelled',
    nativeClasses: ['wizard'],
  },
  {
    id: 'mass-suggestion',
    level: 6,
    school: 'enchantment',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: false, material: "a snake's tongue and a bit of honeycomb or sweet oil" },
    duration: '24 hours',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'move-earth',
    level: 6,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'an iron blade and a small bag of mixed soil' },
    duration: '2 hours',
    nativeClasses: ['druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'otilukes-freezing-sphere',
    level: 6,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '300 feet',
    components: { verbal: true, somatic: true, material: 'a small crystal sphere' },
    duration: 'Instantaneous',
    nativeClasses: ['wizard'],
  },
  {
    id: 'ottos-irresistible-dance',
    level: 6,
    school: 'enchantment',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: false, material: false },
    duration: '1 minute',
    nativeClasses: ['bard', 'wizard'],
  },
  {
    id: 'planar-ally',
    level: 6,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: '10 minutes',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['cleric'],
  },
  {
    id: 'programmed-illusion',
    level: 6,
    school: 'illusion',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a bit of fleece and jade dust worth 25+ GP' },
    duration: 'Until dispelled',
    nativeClasses: ['bard', 'wizard'],
  },
  {
    id: 'summon-fiend',
    level: 6,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 minute',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'a bloody vial worth 600+ GP' },
    duration: '1 hour',
    nativeClasses: ['warlock', 'wizard'],
  },
  {
    id: 'sunbeam',
    level: 6,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a magnifying glass' },
    duration: '1 minute',
    nativeClasses: ['cleric', 'druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'tashas-bubbling-cauldron',
    level: 6,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '10 feet',
    components: { verbal: true, somatic: true, material: 'a gilded ladle worth 500+ GP' },
    duration: '10 minutes',
    nativeClasses: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'transport-via-plants',
    level: 6,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '10 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 round',
    nativeClasses: ['druid'],
  },
  {
    id: 'true-seeing',
    level: 6,
    school: 'divination',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'mushroom powder worth 25+ GP' },
    duration: '1 hour',
    nativeClasses: ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'wall-of-ice',
    level: 6,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a piece of quartz' },
    duration: '10 minutes',
    nativeClasses: ['wizard'],
  },
  {
    id: 'wall-of-thorns',
    level: 6,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a handful of thorns' },
    duration: '10 minutes',
    nativeClasses: ['druid'],
  },
  {
    id: 'wind-walk',
    level: 6,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '1 minute',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a candle' },
    duration: '8 hours',
    nativeClasses: ['druid'],
  },
  {
    id: 'word-of-recall',
    level: 6,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '5 feet',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['cleric'],
  },
  {
    id: 'conjure-celestial',
    level: 7,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '10 minutes',
    nativeClasses: ['cleric'],
  },
  {
    id: 'delayed-blast-fireball',
    level: 7,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '150 feet',
    components: { verbal: true, somatic: true, material: 'a tiny ball of bat guano and sulfur' },
    duration: '1 minute',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  {
    id: 'divine-word',
    level: 7,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Bonus Action',
    range: '30 feet',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['cleric'],
  },
  {
    id: 'draconic-transformation',
    level: 7,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a statuette of a dragon worth 500+ GP' },
    duration: '1 minute',
    nativeClasses: ['druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'dream-of-the-blue-veil',
    level: 7,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: '10 minutes',
    range: '20 feet',
    components: { verbal: true, somatic: true, material: 'a magic item worth 1,000+ GP' },
    duration: '6 hours',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'etherealness',
    level: 7,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 8 hours',
    nativeClasses: ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'finger-of-death',
    level: 7,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'fire-storm',
    level: 7,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '150 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['cleric', 'druid', 'sorcerer'],
  },
  {
    id: 'forcecage',
    level: 7,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '100 feet',
    components: { verbal: true, somatic: true, material: 'ruby dust worth 1,500+ GP' },
    duration: '1 hour',
    nativeClasses: ['bard', 'warlock', 'wizard'],
  },
  {
    id: 'mirage-arcane',
    level: 7,
    school: 'illusion',
    ritual: false,
    concentration: false,
    castingTime: '10 minutes',
    range: 'Sight',
    components: { verbal: true, somatic: true, material: false },
    duration: '10 days',
    nativeClasses: ['bard', 'druid', 'wizard'],
  },
  {
    id: 'mordenkainens-magnificent-mansion',
    level: 7,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: '1 minute',
    range: '300 feet',
    components: { verbal: true, somatic: true, material: 'a miniature portal carved from ivory worth 15+ GP' },
    duration: '24 hours',
    nativeClasses: ['bard', 'wizard'],
  },
  {
    id: 'mordenkainens-sword',
    level: 7,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'a miniature platinum sword worth 250+ GP' },
    duration: '1 minute',
    nativeClasses: ['bard', 'wizard'],
  },
  {
    id: 'plane-shift',
    level: 7,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a forked metal rod worth 250+ GP' },
    duration: 'Instantaneous',
    nativeClasses: ['cleric', 'druid', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'power-word-fortify',
    level: 7,
    school: 'enchantment',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'cleric'],
  },
  {
    id: 'prismatic-spray',
    level: 7,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'sorcerer', 'wizard'],
  },
  {
    id: 'project-image',
    level: 7,
    school: 'illusion',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '500 feet',
    components: { verbal: true, somatic: true, material: 'a statuette of yourself worth 5+ GP' },
    duration: '1 day',
    nativeClasses: ['bard', 'wizard'],
  },
  {
    id: 'regenerate',
    level: 7,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '1 minute',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a prayer wheel' },
    duration: '1 hour',
    nativeClasses: ['bard', 'cleric', 'druid'],
  },
  {
    id: 'resurrection',
    level: 7,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: '1 hour',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a diamond worth 1,000+ GP' },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'cleric'],
  },
  {
    id: 'reverse-gravity',
    level: 7,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '100 feet',
    components: { verbal: true, somatic: true, material: 'a lodestone and iron filings' },
    duration: '1 minute',
    nativeClasses: ['druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'sequester',
    level: 7,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'gold dust worth 100+ GP' },
    duration: 'Until dispelled',
    nativeClasses: ['wizard'],
  },
  {
    id: 'simulacrum',
    level: 7,
    school: 'illusion',
    ritual: false,
    concentration: false,
    castingTime: '12 hours',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'powdered ruby worth 1,500+ GP' },
    duration: 'Until dispelled',
    nativeClasses: ['wizard'],
  },
  {
    id: 'symbol',
    level: 7,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: '1 minute',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'powdered diamond worth 1,000+ GP' },
    duration: 'Until dispelled or triggered',
    nativeClasses: ['bard', 'cleric', 'druid', 'wizard'],
  },
  {
    id: 'teleport',
    level: 7,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '10 feet',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'sorcerer', 'wizard'],
  },
  {
    id: 'temple-of-the-gods',
    level: 7,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: '1 hour',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a holy symbol' },
    duration: '24 hours',
    nativeClasses: ['cleric'],
  },
  {
    id: 'whirlwind',
    level: 7,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '300 feet',
    components: { verbal: true, somatic: false, material: 'a piece of straw' },
    duration: '1 minute',
    nativeClasses: ['druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'crown-of-stars',
    level: 7,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 hour',
    nativeClasses: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'abi-dalzims-horrid-wilting',
    level: 8,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '150 feet',
    components: { verbal: true, somatic: true, material: 'a bit of sponge' },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  {
    id: 'animal-shapes',
    level: 8,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '24 hours',
    nativeClasses: ['druid'],
  },
  {
    id: 'antimagic-field',
    level: 8,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'iron filings' },
    duration: '1 hour',
    nativeClasses: ['cleric', 'wizard'],
  },
  {
    id: 'antipathy-sympathy',
    level: 8,
    school: 'enchantment',
    ritual: false,
    concentration: false,
    castingTime: '1 hour',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a lump of alum soaked in vinegar' },
    duration: '10 days',
    nativeClasses: ['bard', 'druid', 'wizard'],
  },
  {
    id: 'befuddlement',
    level: 8,
    school: 'enchantment',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '150 feet',
    components: { verbal: true, somatic: true, material: 'a handful of clay, crystal, glass, or mineral spheres' },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'druid', 'warlock', 'wizard'],
  },
  {
    id: 'clone',
    level: 8,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: '1 minute',
    range: 'Touch',
    components: {
      verbal: true,
      somatic: true,
      material: 'a diamond worth 1,000+ GP and a sealed vessel worth 2,000+ GP',
    },
    duration: 'Instantaneous',
    nativeClasses: ['wizard'],
  },
  {
    id: 'control-weather',
    level: 8,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: '10 minutes',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'burning incense and bits of earth and wood' },
    duration: '8 hours',
    nativeClasses: ['cleric', 'druid', 'wizard'],
  },
  {
    id: 'dark-star',
    level: 8,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '150 feet',
    components: { verbal: true, somatic: true, material: 'a shard of onyx in a ring worth 150+ GP' },
    duration: '1 minute',
    nativeClasses: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'demiplane',
    level: 8,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Bonus Action',
    range: '60 feet',
    components: { verbal: false, somatic: true, material: false },
    duration: '1 hour',
    nativeClasses: ['warlock', 'wizard'],
  },
  {
    id: 'dominate-monster',
    level: 8,
    school: 'enchantment',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 hour',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'earthquake',
    level: 8,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '500 feet',
    components: { verbal: true, somatic: true, material: 'a pinch of dirt, a rock chip, and a lump of clay' },
    duration: '1 minute',
    nativeClasses: ['cleric', 'druid', 'sorcerer'],
  },
  {
    id: 'glibness',
    level: 8,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: false, material: false },
    duration: '1 hour',
    nativeClasses: ['bard', 'warlock'],
  },
  {
    id: 'holy-aura',
    level: 8,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a tiny reliquary worth 1,000+ GP' },
    duration: '1 minute',
    nativeClasses: ['cleric'],
  },
  {
    id: 'illusory-dragon',
    level: 8,
    school: 'illusion',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: false, somatic: true, material: false },
    duration: '1 minute',
    nativeClasses: ['wizard'],
  },
  {
    id: 'incendiary-cloud',
    level: 8,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '150 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 minute',
    nativeClasses: ['druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'maze',
    level: 8,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '10 minutes',
    nativeClasses: ['wizard'],
  },
  {
    id: 'mind-blank',
    level: 8,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: false },
    duration: '24 hours',
    nativeClasses: ['bard', 'wizard'],
  },
  {
    id: 'power-word-stun',
    level: 8,
    school: 'enchantment',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'sunburst',
    level: 8,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '150 feet',
    components: { verbal: true, somatic: true, material: 'fire and a piece of sunstone' },
    duration: 'Instantaneous',
    nativeClasses: ['druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'telepathy',
    level: 8,
    school: 'divination',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a pair of linked eggs' },
    duration: '24 hours',
    nativeClasses: ['wizard'],
  },
  {
    id: 'tsunami',
    level: 8,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 minute',
    range: 'Sight',
    components: { verbal: true, somatic: true, material: false },
    duration: '6 rounds',
    nativeClasses: ['druid'],
  },
  {
    id: 'astral-projection',
    level: 9,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: '1 hour',
    range: '10 feet',
    components: {
      verbal: true,
      somatic: true,
      material: 'a jacinth worth 1,000+ GP for each creature and a silver bar worth 100+ GP for each',
    },
    duration: 'Until dispelled',
    nativeClasses: ['cleric', 'warlock', 'wizard'],
  },
  {
    id: 'blade-of-disaster',
    level: 9,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 minute',
    nativeClasses: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'foresight',
    level: 9,
    school: 'divination',
    ritual: false,
    concentration: false,
    castingTime: '1 minute',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a hummingbird feather' },
    duration: '8 hours',
    nativeClasses: ['bard', 'druid', 'warlock', 'wizard'],
  },
  {
    id: 'gate',
    level: 9,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a diamond worth 5,000+ GP' },
    duration: '1 minute',
    nativeClasses: ['cleric', 'sorcerer', 'wizard'],
  },
  {
    id: 'imprisonment',
    level: 9,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: '1 minute',
    range: '30 feet',
    components: {
      verbal: true,
      somatic: true,
      material: 'a vellum depiction or statuette of the target and a component worth 500+ GP',
    },
    duration: 'Until dispelled',
    nativeClasses: ['warlock', 'wizard'],
  },
  {
    id: 'invulnerability',
    level: 9,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a small piece of adamantine worth 500+ GP' },
    duration: '10 minutes',
    nativeClasses: ['wizard'],
  },
  {
    id: 'mass-heal',
    level: 9,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['cleric'],
  },
  {
    id: 'mass-polymorph',
    level: 9,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a caterpillar cocoon' },
    duration: '1 hour',
    nativeClasses: ['bard', 'sorcerer', 'wizard'],
  },
  {
    id: 'meteor-swarm',
    level: 9,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '1 mile',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  {
    id: 'power-word-heal',
    level: 9,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'cleric'],
  },
  {
    id: 'power-word-kill',
    level: 9,
    school: 'enchantment',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'prismatic-wall',
    level: 9,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '10 minutes',
    nativeClasses: ['bard', 'wizard'],
  },
  {
    id: 'psychic-scream',
    level: 9,
    school: 'enchantment',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '90 feet',
    components: { verbal: false, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'shapechange',
    level: 9,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a jade circlet worth 1,500+ GP' },
    duration: '1 hour',
    nativeClasses: ['druid', 'wizard'],
  },
  {
    id: 'storm-of-vengeance',
    level: 9,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Sight',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 minute',
    nativeClasses: ['druid'],
  },
  {
    id: 'time-stop',
    level: 9,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  {
    id: 'true-polymorph',
    level: 9,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '30 feet',
    components: {
      verbal: true,
      somatic: true,
      material: 'a drop of mercury, a dollop of gum arabic, and a wisp of smoke',
    },
    duration: '1 hour',
    nativeClasses: ['bard', 'warlock', 'wizard'],
  },
  {
    id: 'true-resurrection',
    level: 9,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: '1 hour',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'diamonds worth 25,000+ GP' },
    duration: 'Instantaneous',
    nativeClasses: ['cleric', 'druid'],
  },
  {
    id: 'weird',
    level: 9,
    school: 'illusion',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 minute',
    nativeClasses: ['warlock', 'wizard'],
  },
  {
    id: 'wish',
    level: 9,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'wizard'],
  },
] as const satisfies readonly SpellDef[];
