import type { SpellDef } from '@/types/spells';

// 2024 PHB level 2 and 3 spells (see spells.ts for the rest of the catalog)
export const SPELLS_L2_L3 = [
  {
    id: 'melfs-acid-arrow',
    level: 2,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: "powdered rhubarb leaf and an adder's stomach" },
    duration: 'Instantaneous',
    nativeClasses: ['wizard'],
  },
  {
    id: 'animal-messenger',
    level: 2,
    school: 'enchantment',
    ritual: true,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a morsel of food' },
    duration: '24 hours',
    nativeClasses: ['bard', 'druid', 'ranger'],
  },
  {
    id: 'arcane-lock',
    level: 2,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'gold dust worth 25+ GP, which the spell consumes' },
    duration: 'Until dispelled',
    nativeClasses: ['wizard'],
  },
  {
    id: 'arcane-vigor',
    level: 2,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  {
    id: 'augury',
    level: 2,
    school: 'divination',
    ritual: true,
    concentration: false,
    castingTime: '1 minute',
    range: 'Self',
    components: {
      verbal: true,
      somatic: true,
      material: 'specially marked sticks, bones, or similar tokens worth 25+ GP',
    },
    duration: 'Instantaneous',
    nativeClasses: ['cleric'],
  },
  {
    id: 'barkskin',
    level: 2,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Bonus Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a handful of oak bark' },
    duration: 'Up to 1 hour',
    nativeClasses: ['druid', 'ranger'],
  },
  {
    id: 'beast-sense',
    level: 2,
    school: 'divination',
    ritual: true,
    concentration: true,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: false, somatic: true, material: false },
    duration: 'Up to 1 hour',
    nativeClasses: ['druid', 'ranger'],
  },
  {
    id: 'blindness-deafness',
    level: 2,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: false, material: false },
    duration: '1 minute',
    nativeClasses: ['bard', 'cleric', 'sorcerer', 'wizard'],
  },
  {
    id: 'branding-smite',
    level: 2,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['paladin'],
  },
  {
    id: 'cloud-of-daggers',
    level: 2,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a sliver of glass' },
    duration: 'Up to 1 minute',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'continual-flame',
    level: 2,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'ruby dust worth 50+ GP, which the spell consumes' },
    duration: 'Until dispelled',
    nativeClasses: ['cleric', 'druid', 'wizard'],
  },
  {
    id: 'cordon-of-arrows',
    level: 2,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '5 feet',
    components: { verbal: true, somatic: true, material: 'four or more arrows or bolts' },
    duration: '8 hours',
    nativeClasses: ['ranger'],
  },
  {
    id: 'crown-of-madness',
    level: 2,
    school: 'enchantment',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'enlarge-reduce',
    level: 2,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a pinch of powdered iron' },
    duration: 'Up to 1 minute',
    nativeClasses: ['bard', 'druid', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'enthrall',
    level: 2,
    school: 'enchantment',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 minute',
    nativeClasses: ['bard', 'warlock'],
  },
  {
    id: 'find-steed',
    level: 2,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: '10 minutes',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['paladin'],
  },
  {
    id: 'find-traps',
    level: 2,
    school: 'divination',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['cleric', 'druid', 'ranger'],
  },
  {
    id: 'flame-blade',
    level: 2,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a leaf of sumac' },
    duration: 'Up to 10 minutes',
    nativeClasses: ['druid'],
  },
  {
    id: 'flaming-sphere',
    level: 2,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '60 feet',
    components: {
      verbal: true,
      somatic: true,
      material: 'a bit of tallow, a pinch of brimstone, and a dusting of powdered iron',
    },
    duration: 'Up to 1 minute',
    nativeClasses: ['druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'gentle-repose',
    level: 2,
    school: 'necromancy',
    ritual: true,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: {
      verbal: true,
      somatic: true,
      material: "a pinch of salt and one copper piece placed on each of the corpse's eyes",
    },
    duration: '10 days',
    nativeClasses: ['cleric', 'wizard'],
  },
  {
    id: 'gust-of-wind',
    level: 2,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self (60-foot line)',
    components: { verbal: true, somatic: true, material: 'a legume seed' },
    duration: 'Up to 1 minute',
    nativeClasses: ['druid', 'ranger', 'sorcerer', 'wizard'],
  },
  {
    id: 'healing-spirit',
    level: 2,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['druid', 'ranger'],
  },
  {
    id: 'heat-metal',
    level: 2,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a piece of iron and a flame' },
    duration: 'Up to 1 minute',
    nativeClasses: ['bard', 'druid'],
  },
  {
    id: 'knock',
    level: 2,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'sorcerer', 'wizard'],
  },
  {
    id: 'levitate',
    level: 2,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '60 feet',
    components: {
      verbal: true,
      somatic: true,
      material:
        'either a small leather loop or a piece of golden wire bent into a cup shape with a long shank on one end',
    },
    duration: 'Up to 10 minutes',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  {
    id: 'locate-animals-or-plants',
    level: 2,
    school: 'divination',
    ritual: true,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a bit of fur from a bloodhound' },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'druid', 'ranger'],
  },
  {
    id: 'locate-object',
    level: 2,
    school: 'divination',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a forked twig' },
    duration: 'Up to 10 minutes',
    nativeClasses: ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'wizard'],
  },
  {
    id: 'magic-mouth',
    level: 2,
    school: 'illusion',
    ritual: true,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: {
      verbal: true,
      somatic: true,
      material: 'a small bit of honeycomb and jade dust worth 10+ GP, which the spell consumes',
    },
    duration: 'Until dispelled',
    nativeClasses: ['bard', 'wizard'],
  },
  {
    id: 'mind-spike',
    level: 2,
    school: 'divination',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: false, somatic: true, material: false },
    duration: 'Up to 1 hour',
    nativeClasses: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'mirror-image',
    level: 2,
    school: 'illusion',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 minute',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'nystuls-magic-aura',
    level: 2,
    school: 'illusion',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a small square of silk' },
    duration: '24 hours',
    nativeClasses: ['wizard'],
  },
  {
    id: 'prayer-of-healing',
    level: 2,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: '10 minutes',
    range: '30 feet',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['cleric'],
  },
  {
    id: 'protection-from-poison',
    level: 2,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 hour',
    nativeClasses: ['cleric', 'druid', 'paladin', 'ranger'],
  },
  {
    id: 'shatter',
    level: 2,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a chip of mica' },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'shining-smite',
    level: 2,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['paladin'],
  },
  {
    id: 'spider-climb',
    level: 2,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a drop of bitumen and a spider' },
    duration: 'Up to 1 hour',
    nativeClasses: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'spike-growth',
    level: 2,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '150 feet',
    components: {
      verbal: true,
      somatic: true,
      material: 'seven sharp thorns or seven small twigs, each sharpened to a point',
    },
    duration: 'Up to 10 minutes',
    nativeClasses: ['druid', 'ranger'],
  },
  {
    id: 'warding-bond',
    level: 2,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: {
      verbal: true,
      somatic: true,
      material: 'a pair of platinum rings worth 50+ GP each, which you and the target must wear for the duration',
    },
    duration: '1 hour',
    nativeClasses: ['cleric', 'paladin'],
  },
  {
    id: 'animate-dead',
    level: 3,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: '1 minute',
    range: '10 feet',
    components: {
      verbal: true,
      somatic: true,
      material: 'a drop of blood, a piece of flesh, and a pinch of bone dust',
    },
    duration: 'Instantaneous',
    nativeClasses: ['cleric', 'wizard'],
  },
  {
    id: 'aura-of-vitality',
    level: 3,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self (30-foot emanation)',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['paladin'],
  },
  {
    id: 'bestow-curse',
    level: 3,
    school: 'necromancy',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['bard', 'cleric', 'wizard'],
  },
  {
    id: 'blinding-smite',
    level: 3,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['paladin'],
  },
  {
    id: 'call-lightning',
    level: 3,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 10 minutes',
    nativeClasses: ['druid'],
  },
  {
    id: 'conjure-animals',
    level: 3,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 hour',
    nativeClasses: ['druid', 'ranger'],
  },
  {
    id: 'conjure-barrage',
    level: 3,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self (60-foot cone)',
    components: { verbal: true, somatic: true, material: 'one piece of ammunition or a thrown weapon' },
    duration: 'Instantaneous',
    nativeClasses: ['ranger'],
  },
  {
    id: 'create-food-and-water',
    level: 3,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['cleric', 'paladin'],
  },
  {
    id: 'elemental-weapon',
    level: 3,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 hour',
    nativeClasses: ['paladin'],
  },
  {
    id: 'feign-death',
    level: 3,
    school: 'necromancy',
    ritual: true,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a pinch of graveyard dirt' },
    duration: '1 hour',
    nativeClasses: ['bard', 'cleric', 'druid', 'wizard'],
  },
  {
    id: 'gaseous-form',
    level: 3,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a pinch of smoke' },
    duration: 'Up to 1 hour',
    nativeClasses: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'glyph-of-warding',
    level: 3,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: '1 hour',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'powdered diamond worth 200+ GP, which the spell consumes' },
    duration: 'Until dispelled or triggered',
    nativeClasses: ['bard', 'cleric', 'wizard'],
  },
  {
    id: 'leomunds-tiny-hut',
    level: 3,
    school: 'evocation',
    ritual: true,
    concentration: false,
    castingTime: '1 minute',
    range: 'Self (10-foot-radius hemisphere)',
    components: { verbal: true, somatic: true, material: 'a crystal bead' },
    duration: '8 hours',
    nativeClasses: ['bard', 'wizard'],
  },
  {
    id: 'lightning-arrow',
    level: 3,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['ranger'],
  },
  {
    id: 'magic-circle',
    level: 3,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: '1 minute',
    range: '10 feet',
    components: {
      verbal: true,
      somatic: true,
      material: 'salt and powdered silver worth 100+ GP, which the spell consumes',
    },
    duration: '1 hour',
    nativeClasses: ['cleric', 'paladin', 'warlock', 'wizard'],
  },
  {
    id: 'major-image',
    level: 3,
    school: 'illusion',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a bit of fleece' },
    duration: 'Up to 10 minutes',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'meld-into-stone',
    level: 3,
    school: 'transmutation',
    ritual: true,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: false },
    duration: '8 hours',
    nativeClasses: ['cleric', 'druid'],
  },
  {
    id: 'phantom-steed',
    level: 3,
    school: 'illusion',
    ritual: true,
    concentration: false,
    castingTime: '1 minute',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 hour',
    nativeClasses: ['wizard'],
  },
  {
    id: 'remove-curse',
    level: 3,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['cleric', 'paladin', 'warlock', 'wizard'],
  },
  {
    id: 'slow',
    level: 3,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a drop of molasses' },
    duration: 'Up to 1 minute',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  {
    id: 'speak-with-dead',
    level: 3,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '10 feet',
    components: { verbal: true, somatic: true, material: 'burning incense' },
    duration: '10 minutes',
    nativeClasses: ['bard', 'cleric'],
  },
  {
    id: 'speak-with-plants',
    level: 3,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self (30-foot emanation)',
    components: { verbal: true, somatic: true, material: false },
    duration: '10 minutes',
    nativeClasses: ['bard', 'druid', 'ranger'],
  },
  {
    id: 'summon-undead',
    level: 3,
    school: 'necromancy',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'a gilded skull worth 300+ GP' },
    duration: 'Up to 1 hour',
    nativeClasses: ['warlock', 'wizard'],
  },
  {
    id: 'tongues',
    level: 3,
    school: 'divination',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: false, material: 'a small clay model of a ziggurat' },
    duration: '1 hour',
    nativeClasses: ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'vampiric-touch',
    level: 3,
    school: 'necromancy',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['warlock', 'wizard'],
  },
  {
    id: 'water-breathing',
    level: 3,
    school: 'transmutation',
    ritual: true,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a short reed or piece of straw' },
    duration: '24 hours',
    nativeClasses: ['druid', 'ranger', 'sorcerer', 'wizard'],
  },
  {
    id: 'water-walk',
    level: 3,
    school: 'transmutation',
    ritual: true,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a piece of cork' },
    duration: '1 hour',
    nativeClasses: ['cleric', 'druid', 'ranger', 'sorcerer'],
  },
  {
    id: 'wind-wall',
    level: 3,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a tiny fan and a feather of exotic origin' },
    duration: 'Up to 1 minute',
    nativeClasses: ['druid', 'ranger'],
  },
] as const satisfies readonly SpellDef[];
