import type { SpellDef } from '@/types/spells';

// 2024 PHB cantrips and level 1 spells not defined in spells.ts.
export const SPELLS_CANTRIPS_L1 = [
  {
    id: 'blade-ward',
    level: 0,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 round',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'eldritch-blast',
    level: 0,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['warlock'],
  },
  {
    id: 'elementalism',
    level: 0,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'friends',
    level: 0,
    school: 'enchantment',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '10 feet',
    components: { verbal: false, somatic: true, material: 'a small amount of makeup applied to the face' },
    duration: 'Up to 1 minute',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'sorcerous-burst',
    level: 0,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer'],
  },
  {
    id: 'starry-wisp',
    level: 0,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'druid'],
  },
  {
    id: 'thaumaturgy',
    level: 0,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['cleric'],
  },
  {
    id: 'thunderclap',
    level: 0,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self (5-foot emanation)',
    components: { verbal: false, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'druid', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'toll-the-dead',
    level: 0,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['cleric', 'warlock', 'wizard'],
  },
  {
    id: 'true-strike',
    level: 0,
    school: 'divination',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: {
      verbal: false,
      somatic: true,
      material: 'a weapon you are proficient with, or a spellcasting focus worth at least 1 cp',
    },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'vicious-mockery',
    level: 0,
    school: 'enchantment',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard'],
  },
  {
    id: 'word-of-radiance',
    level: 0,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self (5-foot emanation)',
    components: { verbal: true, somatic: false, material: 'a sunburst token' },
    duration: 'Instantaneous',
    nativeClasses: ['cleric'],
  },
  {
    id: 'animal-friendship',
    level: 1,
    school: 'enchantment',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a morsel of food' },
    duration: '24 hours',
    nativeClasses: ['bard', 'druid', 'ranger'],
  },
  {
    id: 'armor-of-agathys',
    level: 1,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a cup of water' },
    duration: '1 hour',
    nativeClasses: ['warlock'],
  },
  {
    id: 'color-spray',
    level: 1,
    school: 'illusion',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self (15-foot cone)',
    components: { verbal: true, somatic: true, material: 'a pinch of colorful sand' },
    duration: '1 round',
    nativeClasses: ['bard', 'sorcerer', 'wizard'],
  },
  {
    id: 'comprehend-languages',
    level: 1,
    school: 'divination',
    ritual: true,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a pinch of soot and salt' },
    duration: '1 hour',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'compelled-duel',
    level: 1,
    school: 'enchantment',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: '30 feet',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['paladin'],
  },
  {
    id: 'create-or-destroy-water',
    level: 1,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: {
      verbal: true,
      somatic: true,
      material: 'a drop of water if creating or a few grains of sand if destroying',
    },
    duration: 'Instantaneous',
    nativeClasses: ['cleric', 'druid'],
  },
  {
    id: 'detect-evil-and-good',
    level: 1,
    school: 'divination',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 10 minutes',
    nativeClasses: ['cleric', 'paladin'],
  },
  {
    id: 'detect-poison-and-disease',
    level: 1,
    school: 'divination',
    ritual: true,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a yew leaf' },
    duration: 'Up to 10 minutes',
    nativeClasses: ['cleric', 'druid', 'paladin', 'ranger'],
  },
  {
    id: 'divine-favor',
    level: 1,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['paladin'],
  },
  {
    id: 'divine-smite',
    level: 1,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['paladin'],
  },
  {
    id: 'entangle',
    level: 1,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['druid'],
  },
  {
    id: 'expeditious-retreat',
    level: 1,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 10 minutes',
    nativeClasses: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'feather-fall',
    level: 1,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Reaction',
    range: '60 feet',
    components: { verbal: true, somatic: false, material: 'a small feather or piece of down' },
    duration: '1 minute',
    nativeClasses: ['bard', 'sorcerer', 'wizard'],
  },
  {
    id: 'find-familiar',
    level: 1,
    school: 'conjuration',
    ritual: true,
    concentration: false,
    castingTime: '1 hour',
    range: '10 feet',
    components: { verbal: true, somatic: true, material: 'burning incense worth 10+ GP, which the spell consumes' },
    duration: 'Instantaneous',
    nativeClasses: ['wizard'],
  },
  {
    id: 'floating-disk',
    level: 1,
    school: 'conjuration',
    ritual: true,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a drop of mercury' },
    duration: '1 hour',
    nativeClasses: ['wizard'],
  },
  {
    id: 'goodberry',
    level: 1,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a sprig of mistletoe' },
    duration: '24 hours',
    nativeClasses: ['druid', 'ranger'],
  },
  {
    id: 'grease',
    level: 1,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a bit of pork rind or butter' },
    duration: '1 minute',
    nativeClasses: ['wizard'],
  },
  {
    id: 'hail-of-thorns',
    level: 1,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['ranger'],
  },
  {
    id: 'healing-word',
    level: 1,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Bonus Action',
    range: '60 feet',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'cleric', 'druid'],
  },
  {
    id: 'hex',
    level: 1,
    school: 'enchantment',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'the petrified eye of a newt' },
    duration: 'Up to 1 hour',
    nativeClasses: ['warlock'],
  },
  {
    id: 'ice-knife',
    level: 1,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: false, somatic: true, material: 'a drop of water or piece of ice' },
    duration: 'Instantaneous',
    nativeClasses: ['druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'identify',
    level: 1,
    school: 'divination',
    ritual: true,
    concentration: false,
    castingTime: '1 minute',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a pearl worth 100+ GP and an owl feather' },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'wizard'],
  },
  {
    id: 'illusory-script',
    level: 1,
    school: 'illusion',
    ritual: true,
    concentration: false,
    castingTime: '1 minute',
    range: 'Touch',
    components: { verbal: false, somatic: true, material: 'ink worth 10+ GP, which the spell consumes' },
    duration: '10 days',
    nativeClasses: ['bard', 'warlock', 'wizard'],
  },
  {
    id: 'inflict-wounds',
    level: 1,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['cleric'],
  },
  {
    id: 'jump',
    level: 1,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: "a grasshopper's hind leg" },
    duration: '1 minute',
    nativeClasses: ['druid', 'ranger', 'sorcerer', 'wizard'],
  },
  {
    id: 'mage-armor',
    level: 1,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a piece of cured leather' },
    duration: '8 hours',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  {
    id: 'magic-missile',
    level: 1,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  {
    id: 'purify-food-and-drink',
    level: 1,
    school: 'transmutation',
    ritual: true,
    concentration: false,
    castingTime: 'Action',
    range: '10 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['cleric', 'druid', 'paladin'],
  },
  {
    id: 'sanctuary',
    level: 1,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Bonus Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a shard of glass from a mirror' },
    duration: '1 minute',
    nativeClasses: ['cleric'],
  },
  {
    id: 'searing-smite',
    level: 1,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['paladin'],
  },
  {
    id: 'shield',
    level: 1,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Reaction',
    range: 'Self',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 round',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  {
    id: 'silent-image',
    level: 1,
    school: 'illusion',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a bit of fleece' },
    duration: 'Up to 10 minutes',
    nativeClasses: ['bard', 'sorcerer', 'wizard'],
  },
  {
    id: 'thunderous-smite',
    level: 1,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['paladin'],
  },
  {
    id: 'thunderwave',
    level: 1,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self (15-foot cube)',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'unseen-servant',
    level: 1,
    school: 'conjuration',
    ritual: true,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a bit of string and wood' },
    duration: '1 hour',
    nativeClasses: ['bard', 'warlock', 'wizard'],
  },
  {
    id: 'witch-bolt',
    level: 1,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a twig from a tree struck by lightning' },
    duration: 'Up to 1 minute',
    nativeClasses: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'wrathful-smite',
    level: 1,
    school: 'necromancy',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['paladin'],
  },
  {
    id: 'zephyr-strike',
    level: 1,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['ranger'],
  },
] as const satisfies readonly SpellDef[];
