/**
 * SRD 2024 adventuring gear, tools, foci and equipment packs — GENERATED.
 *
 * Source: 5e-bits/5e-database @ edc5a53c05097a4d9727aeedb6426003a6ffad74 (2024 SRD). Mundane equipment stats
 * are uncopyrightable facts; no attribution required. Regenerate: `npm run gen:items`.
 * Hand-tuned weapons/armor and the original bundled-quantity gear live in items.ts.
 */
import type { GearDef, PackDef } from '@/types/items';

export const SRD_GEAR_CATALOG: readonly ({ readonly type: 'gear' } & GearDef)[] = [
  { type: 'gear', id: "acid", weight: 1, costGp: 25 },
  { type: 'gear', id: "alchemists-fire", weight: 1, costGp: 25 },
  { type: 'gear', id: "alchemists-supplies", weight: 8, costGp: 50 },
  { type: 'gear', id: "amulet", weight: 1, costGp: 5 },
  { type: 'gear', id: "antitoxin", weight: 1, costGp: 50 },
  { type: 'gear', id: "bagpipes", weight: 6, costGp: 30 },
  { type: 'gear', id: "barrel", weight: 70, costGp: 2 },
  { type: 'gear', id: "basket", weight: 2, costGp: 2 },
  { type: 'gear', id: "blanket", weight: 3, costGp: 5 },
  { type: 'gear', id: "block-and-tackle", weight: 5, costGp: 1 },
  { type: 'gear', id: "book", weight: 5, costGp: 25 },
  { type: 'gear', id: "bottle-glass", weight: 2, costGp: 2 },
  { type: 'gear', id: "brewers-supplies", weight: 9, costGp: 20 },
  { type: 'gear', id: "bucket", weight: 2, costGp: 0.05 },
  { type: 'gear', id: "bullets-firearm", weight: 2, costGp: 3 },
  { type: 'gear', id: "calligraphers-supplies", weight: 5, costGp: 10 },
  { type: 'gear', id: "caltrops", weight: 2, costGp: 2 },
  { type: 'gear', id: "carpenters-tools", weight: 6, costGp: 8 },
  { type: 'gear', id: "cartographer-tools", weight: 6, costGp: 15 },
  { type: 'gear', id: "case-crossbow-bolt", weight: 1, costGp: 1 },
  { type: 'gear', id: "case-map-or-scroll", weight: 1, costGp: 1 },
  { type: 'gear', id: "chain", weight: 6, costGp: 5 },
  { type: 'gear', id: "chest", weight: 20, costGp: 50 },
  { type: 'gear', id: "climbers-kit", weight: 8, costGp: 25 },
  { type: 'gear', id: "clothes-fine", weight: 3, costGp: 15 },
  { type: 'gear', id: "cobblers-tools", weight: 5, costGp: 5 },
  { type: 'gear', id: "component-pouch", weight: 1, costGp: 2 },
  { type: 'gear', id: "cooks-utensils", weight: 8, costGp: 1 },
  { type: 'gear', id: "costume", weight: 4, costGp: 5 },
  { type: 'gear', id: "crystal", weight: 1, costGp: 10 },
  { type: 'gear', id: "dice", weight: 0, costGp: 0.1 },
  { type: 'gear', id: "disguise-kit", weight: 3, costGp: 25 },
  { type: 'gear', id: "dragonchess", weight: 0, costGp: 1 },
  { type: 'gear', id: "drum", weight: 3, costGp: 6 },
  { type: 'gear', id: "dulcimer", weight: 10, costGp: 25 },
  { type: 'gear', id: "emblem", weight: 0, costGp: 5 },
  { type: 'gear', id: "flask", weight: 1, costGp: 0.02 },
  { type: 'gear', id: "flute", weight: 1, costGp: 2 },
  { type: 'gear', id: "forgery-kit", weight: 5, costGp: 15 },
  { type: 'gear', id: "glassblowers-tools", weight: 5, costGp: 30 },
  { type: 'gear', id: "grappling-hook", weight: 4, costGp: 2 },
  { type: 'gear', id: "healers-kit", weight: 3, costGp: 5 },
  { type: 'gear', id: "herbalism-kit", weight: 3, costGp: 5 },
  { type: 'gear', id: "holy-water", weight: 1, costGp: 25 },
  { type: 'gear', id: "horn", weight: 2, costGp: 3 },
  { type: 'gear', id: "hunting-trap", weight: 25, costGp: 5 },
  { type: 'gear', id: "ink", weight: 0, costGp: 10 },
  { type: 'gear', id: "ink-pen", weight: 0, costGp: 0.02 },
  { type: 'gear', id: "jewelers-tools", weight: 2, costGp: 25 },
  { type: 'gear', id: "jug", weight: 4, costGp: 0.02 },
  { type: 'gear', id: "ladder", weight: 25, costGp: 0.1 },
  { type: 'gear', id: "lamp", weight: 1, costGp: 0.5 },
  { type: 'gear', id: "lantern-bullseye", weight: 2, costGp: 10 },
  { type: 'gear', id: "leatherworkers-tools", weight: 5, costGp: 5 },
  { type: 'gear', id: "lock", weight: 1, costGp: 10 },
  { type: 'gear', id: "lute", weight: 2, costGp: 35 },
  { type: 'gear', id: "lyre", weight: 2, costGp: 30 },
  { type: 'gear', id: "magnifying-glass", weight: 0, costGp: 100 },
  { type: 'gear', id: "manacles", weight: 6, costGp: 2 },
  { type: 'gear', id: "map", weight: 0, costGp: 1 },
  { type: 'gear', id: "masons-tools", weight: 8, costGp: 10 },
  { type: 'gear', id: "mirror", weight: 0.5, costGp: 5 },
  { type: 'gear', id: "navigators-tools", weight: 2, costGp: 25 },
  { type: 'gear', id: "orb", weight: 3, costGp: 20 },
  { type: 'gear', id: "painters-supplies", weight: 5, costGp: 10 },
  { type: 'gear', id: "pan-flute", weight: 2, costGp: 12 },
  { type: 'gear', id: "paper", weight: 0, costGp: 0.2 },
  { type: 'gear', id: "parchment", weight: 0, costGp: 3 },
  { type: 'gear', id: "perfume", weight: 0, costGp: 5 },
  { type: 'gear', id: "playing-cards", weight: 0, costGp: 0.5 },
  { type: 'gear', id: "poison-basic", weight: 0, costGp: 100 },
  { type: 'gear', id: "poisoners-kit", weight: 2, costGp: 5 },
  { type: 'gear', id: "pole", weight: 7, costGp: 0.05 },
  { type: 'gear', id: "pot-iron", weight: 10, costGp: 2 },
  { type: 'gear', id: "potion-of-healing", weight: 0.5, costGp: 50 },
  { type: 'gear', id: "potters-tools", weight: 3, costGp: 10 },
  { type: 'gear', id: "quiver", weight: 1, costGp: 1 },
  { type: 'gear', id: "ram-portable", weight: 35, costGp: 4 },
  { type: 'gear', id: "reliquary", weight: 2, costGp: 5 },
  { type: 'gear', id: "robe", weight: 1, costGp: 1 },
  { type: 'gear', id: "rod", weight: 2, costGp: 10 },
  { type: 'gear', id: "sack", weight: 1, costGp: 0.01 },
  { type: 'gear', id: "shawm", weight: 1, costGp: 2 },
  { type: 'gear', id: "shovel", weight: 5, costGp: 2 },
  { type: 'gear', id: "signal-whistle", weight: 0, costGp: 0.05 },
  { type: 'gear', id: "smiths-tools", weight: 8, costGp: 20 },
  { type: 'gear', id: "spell-scroll-cantrip", weight: 0, costGp: 30 },
  { type: 'gear', id: "spell-scroll-level-1", weight: 0, costGp: 50 },
  { type: 'gear', id: "spellbook", weight: 3, costGp: 50 },
  { type: 'gear', id: "sprig-of-mistletoe", weight: 0, costGp: 1 },
  { type: 'gear', id: "spyglass", weight: 1, costGp: 1000 },
  { type: 'gear', id: "staff", weight: 4, costGp: 5 },
  { type: 'gear', id: "tent", weight: 20, costGp: 2 },
  { type: 'gear', id: "three-dragon-ante", weight: 0, costGp: 1 },
  { type: 'gear', id: "tinkers-tools", weight: 10, costGp: 50 },
  { type: 'gear', id: "vial", weight: 0, costGp: 1 },
  { type: 'gear', id: "viol", weight: 2, costGp: 30 },
  { type: 'gear', id: "wand", weight: 1, costGp: 10 },
  { type: 'gear', id: "weavers-tools", weight: 5, costGp: 1 },
  { type: 'gear', id: "woodcarvers-tools", weight: 5, costGp: 1 },
  { type: 'gear', id: "yew-wand", weight: 1, costGp: 10 },
];

export const SRD_PACK_CATALOG: readonly ({ readonly type: 'pack' } & PackDef)[] = [
  {
    type: 'pack',
    id: "diplomat-pack",
    costGp: 39,
    contents: [
      { itemId: "chest", quantity: 1 },
      { itemId: "clothes-fine", quantity: 1 },
      { itemId: "ink", quantity: 1 },
      { itemId: "ink-pen", quantity: 5 },
      { itemId: "lamp", quantity: 1 },
      { itemId: "case-map-or-scroll", quantity: 2 },
      { itemId: "flask", quantity: 4 },
      { itemId: "oil-flasks-2", quantity: 4 },
      { itemId: "paper", quantity: 5 },
      { itemId: "parchment", quantity: 5 },
      { itemId: "perfume", quantity: 1 },
      { itemId: "tinderbox", quantity: 1 },
    ],
  },
  {
    type: 'pack',
    id: "entertainers-pack",
    costGp: 40,
    contents: [
      { itemId: "backpack", quantity: 1 },
      { itemId: "bedroll", quantity: 1 },
      { itemId: "costume", quantity: 2 },
      { itemId: "candles-5", quantity: 5 },
      { itemId: "rations-10", quantity: 5 },
      { itemId: "waterskin", quantity: 1 },
      { itemId: "disguise-kit", quantity: 1 },
    ],
  },
  {
    type: 'pack',
    id: "priests-pack",
    costGp: 33,
    contents: [
      { itemId: "backpack", quantity: 1 },
      { itemId: "blanket", quantity: 1 },
      { itemId: "holy-water", quantity: 1 },
      { itemId: "lamp", quantity: 1 },
      { itemId: "rations-10", quantity: 7 },
      { itemId: "robe", quantity: 1 },
      { itemId: "tinderbox", quantity: 1 },
    ],
  },
  {
    type: 'pack',
    id: "scholars-pack",
    costGp: 40,
    contents: [
      { itemId: "backpack", quantity: 1 },
      { itemId: "blanket", quantity: 1 },
      { itemId: "book", quantity: 1 },
      { itemId: "ink", quantity: 1 },
      { itemId: "ink-pen", quantity: 1 },
      { itemId: "lamp", quantity: 1 },
      { itemId: "oil-flasks-2", quantity: 10 },
      { itemId: "parchment", quantity: 10 },
      { itemId: "tinderbox", quantity: 1 },
    ],
  },
];
